#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb  3 17:21:19 2018

@author: root
"""

import pymysql

host = '114.32.60.100'

def create_dataset():  
    conn = ( pymysql.connect(host = host,# SQL IP
                             port = 3306,
                             user='chatbot',# 帳號
                             password='w3429iom',# 密碼
                             database='chatbot',  # 資料庫名稱
                             charset="utf8") )   #  編碼  
    c=conn.cursor()
    sql_name = 'remain_train_ticket_info'
    sql_string = ( 'create table ' + sql_name + '( i int(10), train_no text(100),'+
    'from_station text(100),start_date text(100),start_time text(100),ticket_amount text(100),'  +
    'to_station text(100),'  +
    '  sender_id text(100))' )
    
    c.execute( sql_string )# 建立新的 SQL file
    c.execute('ALTER TABLE `'+ sql_name +'` ADD id BIGINT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY;')
    c.close() # 關閉與 SQL 的連接
    conn.close()# 關閉與 SQL 的連接
#--------------------------------------------------------------
    
    
    
